# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

jobs:
  lint-check:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: "Do Lint Checks"
          run: |
          pip install poetry==1.0.0
          poetry install
          poetry run black --check .

workflows:
  ci-lint-workflow:
    jobs:
      - lint-check
