name: Upgrade Helm chart

on:
  schedule:
    - cron: "*/2 * * * *"
    - cron: "*/1 * * * *"

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setenvrelease
        if: github.event.schedule=='*/2 * * * *'
        run: |
          echo 'PARAM_ENV=release' >> $GITHUB_ENV

      - name: setenvprod
        if: github.event.schedule=='*/1 * * * *'
        run: |
          echo 'PARAM_ENV=prod' >> $GITHUB_ENV

      - name: check env value  # check env value
        run: |
          echo $PARAM_ENV

      - name: Upgrade Helm chart
        env:
          PARAM_ENV: $PARAM_ENV
        run: /bin/bash ./check_env.sh
