name: test
on:
  workflow_dispatch:
jobs:
   a:
    name: a
    runs-on: ubuntu-latest
    steps:
      - run: echo "A1213416546557" > ~/run_result.txt
      - id: set
        run: |
          "vercel-dp-url=$(cat ~/run_result.txt)"
          echo "DP_URL=$vercel-dp-url" >> $GITHUB_ENV
   b:
    name: b
    runs-on: ubuntu-latest
    needs:
      - a
    if: needs.a.outputs.run_job_b == 'yes'
    steps:
      - run: |
         echo ${{ env.DP_URL }}
         exit 1
   c:
    name: c
    runs-on: ubuntu-latest
    needs:
      - a
      - b
    if: needs.b.result == 'success' || needs.b.result == 'skipped'
    steps:
      - run: echo "C"
