name: test
on:
  workflow_dispatch:
jobs:
   a:
    name: a
    runs-on: ubuntu-latest
    steps:
      - id: set
        run: |
          echo "A1213416546557" > ~/run_result.txt
          echo "::set-output name=run_job_b::$(cat ~/run_result.txt)"
    outputs:
      run_job_b: ${{ steps.set.outputs.run_job_b }}

   b:
    name: b
    runs-on: ubuntu-latest
    needs:
      - a
    if: needs.a.outputs.run_job_b == 'A1213416546557'
    steps:
      - run: exit 1
   c:
    name: c
    runs-on: ubuntu-latest
    needs:
      - a
      - b
    if: needs.b.result == 'success' || needs.b.result == 'skipped'
    steps:
      - run: echo "C"
