name: test
on:
  workflow_dispatch:
jobs:
   a:
    name: a
    runs-on: ubuntu-latest
    steps:
      - id: set
        run: |
          echo "A1213416546557" > ~/run_result.txt
          echo "DP_URL=$(cat ~/run_result.txt)" >> $GITHUB_ENV
   b:
    name: b
    runs-on: ubuntu-latest
    needs:
      - a
    if: success()
    steps:
      - run: |
         echo ${{ env.DP_URL }}
         exit 1
   c:
    name: c
    runs-on: ubuntu-latest
    needs:
      - a
      - b
    if: needs.b.result == 'success' || needs.b.result == 'skipped'
    steps:
      - run: echo "C"
